# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
        # If specified, run `pnpm install`
        run_install: true
    - run: pnpm run build
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        # Path of the directory containing the static assets.
        path: src/.vuepress/dist/
        # Duration after which artifact will expire in days.
        retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.2
        with:
          # Maximum number of status report errors before cancelling a deployment (default: 10)
          error_count: 2


